import type { Client } from './types';

/* ── Mock Client Data ─────────────────────────────────────────── */
export const CLIENTS: Client[] = [
  {
    id: 'cl1',
    name: 'HDFC Securities',
    industry: 'Broking',
    status: 'active',
    tier: 'Key Account',
    openPositions: 4,
    pocName: 'Rohan Bansal',
    location: 'Mumbai',
    email: 'hr@hdfcsec.com',
    phone: '+91 22 4285 8484',
    website: 'https://www.hdfcsec.com',
    gst: '27AAACH0997R1ZG',
    linkedin: 'https://linkedin.com/company/hdfcsec',
    agreementDate: '2024-06-15',
    commercials: '8.33%',
    paymentPeriod: '45 days',
    replacementPeriod: '90 days',
    hiringPOC: { name: 'Rohan Bansal', email: 'rohan.bansal@hdfcsec.com', phone: '+91 98200 11111' },
    paymentPOC: { name: 'Priya Mehta', email: 'priya.mehta@hdfcsec.com', phone: '+91 98200 22222' },
  },
  {
    id: 'cl2',
    name: 'Kotak Securities',
    industry: 'Broking',
    status: 'active',
    tier: 'Key Account',
    openPositions: 3,
    pocName: 'Kavita Iyer',
    location: 'Mumbai',
    email: 'hiring@kotak.com',
    phone: '+91 22 6171 7300',
    website: 'https://www.kotaksecurities.com',
    gst: '—',
    linkedin: 'https://linkedin.com/company/kotaksecurities',
    agreementDate: '2024-08-01',
    commercials: '8.33%',
    paymentPeriod: '30 days',
    replacementPeriod: '90 days',
    hiringPOC: { name: 'Kavita Iyer', email: 'kavita.iyer@kotak.com', phone: '+91 98200 22221' },
    paymentPOC: { name: 'Amit Kadam', email: 'amit.kadam@kotak.com', phone: '+91 98200 22222' },
  },
  {
    id: 'cl3',
    name: 'Nuvama Wealth',
    industry: 'Wealth Management',
    status: 'active',
    tier: 'Standard',
    openPositions: 2,
    pocName: 'Sameer Rao',
    location: 'Bengaluru',
    email: 'talent@nuvama.com',
    phone: '+91 80 4567 8901',
    website: 'https://www.nuvama.com',
    gst: '29AABCN1234R1Z5',
    linkedin: 'https://linkedin.com/company/nuvama',
    agreementDate: '2024-09-10',
    commercials: '10%',
    paymentPeriod: '60 days',
    replacementPeriod: '60 days',
    hiringPOC: { name: 'Sameer Rao', email: 'sameer.rao@nuvama.com', phone: '+91 98450 33333' },
    paymentPOC: { name: 'Deepa Nair', email: 'deepa.nair@nuvama.com', phone: '+91 98450 44444' },
  },
  {
    id: 'cl4',
    name: 'Axis AMC',
    industry: 'AMC',
    status: 'active',
    tier: 'Standard',
    openPositions: 2,
    pocName: 'Ritika Mehra',
    location: 'Mumbai',
    email: 'hr@axismf.com',
    phone: '+91 22 4325 3232',
    website: 'https://www.axismf.com',
    gst: '27AABCA4567R1Z8',
    linkedin: 'https://linkedin.com/company/axismf',
    agreementDate: '2024-07-20',
    commercials: '8.33%',
    paymentPeriod: '45 days',
    replacementPeriod: '90 days',
    hiringPOC: { name: 'Ritika Mehra', email: 'ritika.mehra@axismf.com', phone: '+91 98200 55555' },
    paymentPOC: { name: 'Vikram Shah', email: 'vikram.shah@axismf.com', phone: '+91 98200 66666' },
  },
  {
    id: 'cl5',
    name: 'Motilal Oswal',
    industry: 'Broking',
    status: 'active',
    tier: 'Standard',
    openPositions: 2,
    pocName: 'Pranav Deshmukh',
    location: 'Mumbai',
    email: 'careers@motilaloswal.com',
    phone: '+91 22 3980 4263',
    website: 'https://www.motilaloswal.com',
    gst: '27AABCM7890R1Z3',
    linkedin: 'https://linkedin.com/company/motilaloswal',
    agreementDate: '2024-05-01',
    commercials: '8.33%',
    paymentPeriod: '30 days',
    replacementPeriod: '60 days',
    hiringPOC: { name: 'Pranav Deshmukh', email: 'pranav.d@motilaloswal.com', phone: '+91 98200 77777' },
    paymentPOC: { name: 'Sneha Gupta', email: 'sneha.g@motilaloswal.com', phone: '+91 98200 88888' },
  },
  {
    id: 'cl6',
    name: 'Bajaj Finserv',
    industry: 'NBFC',
    status: 'active',
    tier: 'Key Account',
    openPositions: 3,
    pocName: 'Vandana K.',
    location: 'Pune',
    email: 'talent@bajajfinserv.in',
    phone: '+91 20 6720 2000',
    website: 'https://www.bajajfinserv.in',
    gst: '27AABCB1234R1Z9',
    linkedin: 'https://linkedin.com/company/bajajfinserv',
    agreementDate: '2024-04-15',
    commercials: '10%',
    paymentPeriod: '45 days',
    replacementPeriod: '90 days',
    hiringPOC: { name: 'Vandana K.', email: 'vandana.k@bajajfinserv.in', phone: '+91 98500 99999' },
    paymentPOC: { name: 'Ravi Sharma', email: 'ravi.sharma@bajajfinserv.in', phone: '+91 98500 11111' },
  },
  {
    id: 'cl7',
    name: 'HDFC Life',
    industry: 'Insurance',
    status: 'inactive',
    tier: 'Standard',
    openPositions: 1,
    pocName: 'Rakesh Menon',
    location: 'Mumbai',
    email: 'hr@hdfclife.com',
    phone: '+91 22 6782 8282',
    website: 'https://www.hdfclife.com',
    gst: '27AABCH5678R1Z2',
    linkedin: 'https://linkedin.com/company/hdfclife',
    agreementDate: '2023-12-01',
    commercials: '8.33%',
    paymentPeriod: '60 days',
    replacementPeriod: '90 days',
    hiringPOC: { name: 'Rakesh Menon', email: 'rakesh.menon@hdfclife.com', phone: '+91 98200 33333' },
    paymentPOC: { name: 'Anita Roy', email: 'anita.roy@hdfclife.com', phone: '+91 98200 44444' },
  },
];
